services:
  - type: web
    runtime: node
    name: dextr-deepagent-poc
    buildCommand: npm install && npm run build
    preDeployCommand: npm run migrate
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
